# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-11 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190112_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
